### ISSUE TITLE
[BUG] With HUD loaded, no orbits are visible

### ISSUE THREAD

**Issue by schlosrat** [DunaColonist/hud#1]
This is a great looking mod! I really like the graphics. The trouble is with it loaded there are no orbit lines displayed in the map view. Not for the active vessel or for any other vessel in the vicinity. This is a no-go for me. I'll keep an eye on your mod, but it's not useful to me if it comes at a cost of not being able to see any orbit lines.

**Comment by BertrandDechoux** [comment]
Thanks for your feedback. I did not see this one here on GitHub. Thanks for posting it also on the forum.

As explained in https://forum.kerbalspaceprogram.com/index.php?/topic/215686-hud-head-up-display/, it has been solved.

So I am closing this issue.
